""" Provides a class to interact with the database """

import os
from google.auth.credentials import AnonymousCredentials
from google.cloud.firestore import Client
from database.database_abstract import DatabaseAbstract


class LocalDatabase(DatabaseAbstract):
    """Write to local database"""

    def __init__(self):
        super().__init__()
        project_id = "dummy-project-id"
        os.environ["FIRESTORE_EMULATOR_HOST"] = "localhost:8080"

        cred = AnonymousCredentials()
        self.db = Client(project=project_id, credentials=cred)

        self._init_database_handlers()

    def verify_id_token(self, id_token: str, user_id: str):
        """
        Verify if a given ID token generated by firebase Auth matches compared to the user ID

        Args:
            id_token (str): The ID token
            user_id (str): The user ID
        """
        return True
