name: Create Release

on:
    push:
      tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
    create_release:
        runs-on: ubuntu-latest
        steps:
          - name: Release
            uses: docker://antonyurchenko/git-release:v5
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                args: build/*.zip
