name: Push tag on dev branch

on:
  push:
    branches:
      - development

jobs:  
  push_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup github
        run: |
          git config --global user.email "$EMAIL_GITHUB"
          git config --global user.name "jacob-macleod"

      - name: Push the new tags
        run: |
          git tag $(grep -Eo "__version__ = \"[0-9]+\.[0-9]+\.[0-9]+\"" "backend/__init__.py" | awk -F '"' '{print $2}')
          git push --tags --force
