name: Terraform Update

on:
  push:
    branches:
      - migrate_to_cloud_run

jobs:  
  push_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install node
        run: |
          sudo apt-get update
          sudo apt install nodejs npm
          cd frontend
          npm install -g create-react-app
          npm install

      - name: Build the React App for Deployment
        run: |
          echo "$MAILCHIMP_API_KEY" > frontend/src/api/secretKeys.js
          cd frontend
          npm run build
          rm -rf frontend/node_modules
        env:
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}

      - name: Build Docker Image
        run: |
          echo "Docker image name"
          export GCP_DOCKER_IMAGE_NAME=europe-west1-docker.pkg.dev/dev-vms-jacob/dolphin-flashcards-mirror/flashcard-app
          echo $GCP_DOCKER_IMAGE_NAME
          echo $GCP_DOCKER_IMAGE_NAME:latest
          docker build -t $GCP_DOCKER_IMAGE_NAME/dev-vms-jacob/dolphin-flashcards-mirror/flashcard-app:latest .
        env:
          GCP_DOCKER_IMAGE_NAME: ${{ secrets.GCP_DOCKER_IMAGE_NAME }}

      - name: Set up GCP credentials
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli
          echo "$GCP_CLOUD_RUN_AND_ARTIFACT_SA" > gcp_credentials.json
          gcloud auth configure-docker $GCP_ARTIFACT_REGISTRY_LOCATION
        env:
          GCP_ARTIFACT_REGISTRY_LOCATION: ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}

      - name: Push Docker Image to GCP Artifact Registry
        run: |
          echo "Pushing to $GCP_DOCKER_IMAGE_NAME/dev-vms-jacob/dolphin-flashcards-mirror/flashcard-app:latest"
          docker push $GCP_DOCKER_IMAGE_NAME/dev-vms-jacob/dolphin-flashcards-mirror/flashcard-app:latest
        env:
          GCP_DOCKER_IMAGE_NAME: ${{ secrets.GCP_DOCKER_IMAGE_NAME }}

      - name: Update Google Cloud Run
        run: |
            sudo apt-get install -y terraform
            export GOOGLE_APPLICATION_CREDENTIALS=$GCP_CLOUD_RUN_AND_ARTIFACT_SA
            cd terraform
            terraform apply
